export interface MessageT {
	id: string | number
	senderProfilePicUrl: string
	senderName: string
	senderTitle: string
	senderCompany: string
	message: string
	timestamp: string
	senderLocation?: string
}

export const mockedMessages: MessageT[] = [
	{
		id: 1,
		senderName: 'John Doe',
		senderTitle: 'Software Engineer',
		senderCompany: 'Google',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
		message: 'Hey, let’s catch up soon!',
		timestamp: '2025-01-24T14:30:00Z',
	},
	{
		id: 2,
		senderName: 'Jane Smith',
		senderTitle: 'Product Manager',
		senderCompany: 'Amazon',
		senderLocation: 'Seattle, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
		message: 'Can we reschedule our meeting?',
		timestamp: '2025-01-23T11:15:00Z',
	},
	{
		id: 3,
		senderName: 'Michael Johnson',
		senderTitle: 'Data Scientist',
		senderCompany: 'Facebook',
		senderLocation: 'Menlo Park, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
		message: 'Thanks for the update!',
		timestamp: '2025-01-22T16:45:00Z',
	},
	{
		id: 4,
		senderName: 'Alice Brown',
		senderTitle: 'UX Designer',
		senderCompany: 'Apple',
		senderLocation: 'Cupertino, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
		message: 'Great design work on the new project!',
		timestamp: '2025-01-21T08:30:00Z',
	},
	{
		id: 5,
		senderName: 'Chris Williams',
		senderTitle: 'Software Engineer',
		senderCompany: 'Spotify',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
		message: 'Let’s sync up tomorrow!',
		timestamp: '2025-01-20T19:00:00Z',
	},
	{
		id: 6,
		senderName: 'Sarah Lee',
		senderTitle: 'Product Manager',
		senderCompany: 'Netflix',
		senderLocation: 'Los Gatos, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
		message: 'I’ve updated the roadmap, check it out!',
		timestamp: '2025-01-19T10:15:00Z',
	},
	{
		id: 7,
		senderName: 'David Martinez',
		senderTitle: 'Backend Developer',
		senderCompany: 'Uber',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
		message: 'Can you review the latest API changes?',
		timestamp: '2025-01-18T17:45:00Z',
	},
	{
		id: 8,
		senderName: 'Emily Taylor',
		senderTitle: 'Data Scientist',
		senderCompany: 'LinkedIn',
		senderLocation: 'Sunnyvale, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
		message: 'I found some interesting insights for our project!',
		timestamp: '2025-01-17T12:30:00Z',
	},
	{
		id: 9,
		senderName: 'Jack Wilson',
		senderTitle: 'Software Engineer',
		senderCompany: 'Google',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
		message: 'Let’s discuss the new feature tomorrow.',
		timestamp: '2025-01-16T14:45:00Z',
	},
	{
		id: 10,
		senderName: 'Olivia Moore',
		senderTitle: 'Product Manager',
		senderCompany: 'Amazon',
		senderLocation: 'Seattle, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
		message: 'The team is ready for the next sprint!',
		timestamp: '2025-01-15T11:00:00Z',
	},
	{
		id: 11,
		senderName: 'Daniel Scott',
		senderTitle: 'DevOps Engineer',
		senderCompany: 'Microsoft',
		senderLocation: 'Redmond, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
		message: 'Please update the server configuration.',
		timestamp: '2025-01-14T15:30:00Z',
	},
	{
		id: 12,
		senderName: 'Grace Harris',
		senderTitle: 'Frontend Developer',
		senderCompany: 'Twitter',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
		message: 'Check out the latest changes to the UI!',
		timestamp: '2025-01-13T13:00:00Z',
	},
	{
		id: 13,
		senderName: 'Matthew Clark',
		senderTitle: 'Backend Developer',
		senderCompany: 'Facebook',
		senderLocation: 'Menlo Park, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/13.jpg',
		message: 'Let’s test the new API endpoints today.',
		timestamp: '2025-01-12T09:00:00Z',
	},
	{
		id: 14,
		senderName: 'Sophia Young',
		senderTitle: 'Product Designer',
		senderCompany: 'Dropbox',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
		message: 'Can you review the design mockups?',
		timestamp: '2025-01-11T18:15:00Z',
	},
	{
		id: 15,
		senderName: 'Matthew Green',
		senderTitle: 'Software Engineer',
		senderCompany: 'Slack',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
		message: 'The new feature is ready for deployment.',
		timestamp: '2025-01-10T07:30:00Z',
	},
	{
		id: 16,
		senderName: 'Lucas Adams',
		senderTitle: 'Software Engineer',
		senderCompany: 'Spotify',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/16.jpg',
		message: 'I need help with a bug in the code.',
		timestamp: '2025-01-09T19:45:00Z',
	},
	{
		id: 17,
		senderName: 'Amelia Thompson',
		senderTitle: 'Product Manager',
		senderCompany: 'Apple',
		senderLocation: 'Cupertino, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/17.jpg',
		message: 'Can you review the project goals?',
		timestamp: '2025-01-08T17:00:00Z',
	},
	{
		id: 18,
		senderName: 'Ryan Robinson',
		senderTitle: 'Software Engineer',
		senderCompany: 'Uber',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/18.jpg',
		message: 'Let’s sync up on the new requirements.',
		timestamp: '2025-01-07T16:45:00Z',
	},
	{
		id: 19,
		senderName: 'Chloe Wright',
		senderTitle: 'Frontend Developer',
		senderCompany: 'Netflix',
		senderLocation: 'Los Gatos, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/19.jpg',
		message: 'The homepage redesign is live!',
		timestamp: '2025-01-06T14:00:00Z',
	},
	{
		id: 20,
		senderName: 'Benjamin Lee',
		senderTitle: 'Data Scientist',
		senderCompany: 'Amazon',
		senderLocation: 'Seattle, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/20.jpg',
		message: 'The data analysis report is ready.',
		timestamp: '2025-01-05T12:30:00Z',
	},
	{
		id: 21,
		senderName: 'Ella Harris',
		senderTitle: 'Product Manager',
		senderCompany: 'Microsoft',
		senderLocation: 'Redmond, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
		message: 'Can we discuss the budget adjustments?',
		timestamp: '2025-01-04T11:00:00Z',
	},
	{
		id: 1,
		senderName: 'David Mitchell',
		senderTitle: 'Frontend Developer',
		senderCompany: 'Google',
		senderLocation: 'Mountain View, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
		message: 'I’ve pushed the latest updates to the repo.',
		timestamp: '2025-01-24T08:15:00Z',
	},
	{
		id: 2,
		senderName: 'Grace Turner',
		senderTitle: 'UX Designer',
		senderCompany: 'Adobe',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
		message: 'How do you feel about the new color scheme?',
		timestamp: '2025-01-23T13:20:00Z',
	},
	{
		id: 3,
		senderName: 'Liam Harris',
		senderTitle: 'Backend Engineer',
		senderCompany: 'Amazon',
		senderLocation: 'Seattle, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
		message: 'Can you send me the latest API documentation?',
		timestamp: '2025-01-22T09:30:00Z',
	},
	{
		id: 4,
		senderName: 'Sophia Rogers',
		senderTitle: 'Product Manager',
		senderCompany: 'Twitter',
		senderLocation: 'New York, NY',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
		message: 'The meeting is scheduled for 10 AM tomorrow.',
		timestamp: '2025-01-21T10:45:00Z',
	},
	{
		id: 5,
		senderName: 'William Scott',
		senderTitle: 'DevOps Engineer',
		senderCompany: 'Microsoft',
		senderLocation: 'Redmond, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
		message: 'The new server is up and running!',
		timestamp: '2025-01-20T15:00:00Z',
	},
	{
		id: 6,
		senderName: 'Mia Collins',
		senderTitle: 'Frontend Developer',
		senderCompany: 'GitHub',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
		message: 'The latest pull request is ready for review.',
		timestamp: '2025-01-19T11:10:00Z',
	},
	{
		id: 7,
		senderName: 'Ethan Thompson',
		senderTitle: 'Data Scientist',
		senderCompany: 'Facebook',
		senderLocation: 'Menlo Park, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
		message: 'I found an issue with the data pipeline.',
		timestamp: '2025-01-18T12:30:00Z',
	},
	{
		id: 8,
		senderName: 'Harper Wright',
		senderTitle: 'QA Engineer',
		senderCompany: 'Slack',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
		message: 'The new features passed the test suite.',
		timestamp: '2025-01-17T14:40:00Z',
	},
	{
		id: 9,
		senderName: 'Matthew Clark',
		senderTitle: 'Software Engineer',
		senderCompany: 'LinkedIn',
		senderLocation: 'Sunnyvale, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
		message: 'The refactor is complete, looking good!',
		timestamp: '2025-01-16T13:00:00Z',
	},
	{
		id: 10,
		senderName: 'Olivia King',
		senderTitle: 'Project Manager',
		senderCompany: 'Spotify',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
		message: 'Please check the updated timeline.',
		timestamp: '2025-01-15T16:50:00Z',
	},
	{
		id: 11,
		senderName: 'Jackson Lee',
		senderTitle: 'Full Stack Developer',
		senderCompany: 'Airbnb',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
		message: 'The new search functionality is live.',
		timestamp: '2025-01-14T10:15:00Z',
	},
	{
		id: 12,
		senderName: 'Ava White',
		senderTitle: 'HR Manager',
		senderCompany: 'Zoom',
		senderLocation: 'San Jose, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
		message: 'We need to schedule interviews for next week.',
		timestamp: '2025-01-13T08:00:00Z',
	},
	{
		id: 13,
		senderName: 'James Johnson',
		senderTitle: 'Software Engineer',
		senderCompany: 'Google',
		senderLocation: 'Mountain View, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/13.jpg',
		message: 'I’ve updated the dependencies for the project.',
		timestamp: '2025-01-12T09:45:00Z',
	},
	{
		id: 14,
		senderName: 'Isabella Davis',
		senderTitle: 'Product Designer',
		senderCompany: 'Apple',
		senderLocation: 'Cupertino, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
		message: 'Here are the wireframes for review.',
		timestamp: '2025-01-11T18:15:00Z',
	},
	{
		id: 15,
		senderName: 'Leo Anderson',
		senderTitle: 'Backend Engineer',
		senderCompany: 'Stripe',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
		message: 'The new API endpoints are working as expected.',
		timestamp: '2025-01-10T16:30:00Z',
	},
	{
		id: 16,
		senderName: 'Ella Miller',
		senderTitle: 'Product Manager',
		senderCompany: 'Microsoft',
		senderLocation: 'Redmond, WA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/16.jpg',
		message: 'Can we get an update on the latest design?',
		timestamp: '2025-01-09T14:00:00Z',
	},
	{
		id: 17,
		senderName: 'Oliver Moore',
		senderTitle: 'DevOps Engineer',
		senderCompany: 'Dropbox',
		senderLocation: 'Remote',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/17.jpg',
		message: 'Please review the build configuration.',
		timestamp: '2025-01-08T13:45:00Z',
	},
	{
		id: 18,
		senderName: 'Charlotte Green',
		senderTitle: 'QA Engineer',
		senderCompany: 'Uber',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/women/18.jpg',
		message: 'The testing is complete, everything looks good.',
		timestamp: '2025-01-07T11:00:00Z',
	},
	{
		id: 19,
		senderName: 'Benjamin Wright',
		senderTitle: 'Data Scientist',
		senderCompany: 'Slack',
		senderLocation: 'San Francisco, CA',
		senderProfilePicUrl: 'https://randomuser.me/api/portraits/men/19.jpg',
		message: 'I’ve cleaned the data set for the analysis.',
		timestamp: '2025-01-06T10:00:00Z',
	},
]
